Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Ingredient.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_static.Models
{
    [Table("Ingredient")]
    public class Ingredient
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        
        public List<Pizza> Pizzas { get; set; }
    }
}

Models/Pizza.cs
using la_mia_pizzeria_static.Validations;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_static.Models
{
    [Table("Pizza")]
    public class Pizza
    {
        public Pizza()
        {

        }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(20)]
        public string Name { get; set; }

        [Required]
        [CustomDescription]
        public string Description { get; set; }

        [Required]
        [Range(0, 20)]

        public decimal Price { get; set; }

        [Required]
        public string ImageUrl { get; set; }

        public List<Ingredient>? Ingredients { get; set; }
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PizzaList()
        {
            return View();
        }

        public IActionResult Prenota()
        {
            return View();
        }
        public IActionResult Contatti()
        {
            return View();
        }
        public IActionResult Impasto()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PizzeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzeController : Controller
    {
        public IActionResult Index()
        {
            PizzaContext context = new PizzaContext();
            
            IQueryable<Pizza> pizzas = context.Pizzas;
            return View(pizzas);
            
        }

        [HttpGet]
        public IActionResult CreateForm()
        {
/*            PizzaContext context = new PizzaContext();
            List<Ingredient> ingredients = context.Ingredients.ToList();*/

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pizza pizza)
        {

            if (!ModelState.IsValid)
            {
                return View("CreateForm", pizza);
            }

            using(PizzaContext context = new PizzaContext())
            {
                List<Ingredient> ingredients = context.Ingredients.ToList();
                pizza.Ingredients = ingredients;
                context.Add(pizza);
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            PizzaContext context = new PizzaContext();
            Pizza pizza = context.Pizzas.Where(pizza => pizza.Id == id).Include("Ingredients").FirstOrDefault();
            return View(pizza);
        }
    }
}

Views/Home/Contatti.cshtml
@{
    ViewData["Title"] = "Home";
}

Views/Home/Impasto.cshtml
@{
    ViewData["Title"] = "Home";
}

Views/Home/Prenota.cshtml
@{
    ViewData["Title"] = "Home";
}

Views/Pizze/CreateForm.cshtml
@model la_mia_pizzeria_static.Models.Pizza

@{
    ViewData["Title"] = "Aggiungi Pizza";
}



<h4>Pizza</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Pizze" asp-action="Create" method="post">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pizze/Details.cshtml
@model Pizza

<div class="container d-flex">
    <div class="flex-grow-1">
        <img class="img-fluid" src=@Model.ImageUrl />
    </div>
    <div class="flex-grow-2 ps-5">
        <h2>@Model.Name</h2>
        <p>@Model.Description</p>
        <h3>Ingredients: </h3>
        @foreach(Ingredient ingredient in @Model.Ingredients)
        {
            <p class="py-0 ps-3 my-0">@ingredient.Name</p>
        }
        <p class="py-4">@Model.Price</p>
    </div>
</div>

Views/Pizze/Index.cshtml
@model IQueryable<Pizza>

@{
    ViewData["Title"] = "Le Nostre Pizze";
}

@if(Model.Count() == 0)
{
    <div class="container text-center">
        <h1>NON CI SONO PIZZE DISPONIBILI IN ELENCO</h1>
    </div>
}
else
{
    <section class="wrapper">
    <div class="container">

        <div class="row">
                @foreach(Pizza pizza in Model)
                {
                    <div class="col-sm-12 col-md-6 col-lg-4 mb-4">
                        <a href="@Url.Action("Details", "Pizze", new {Id = pizza.Id})">
                            <div class="card text-white card-has-bg click-col" style="background-image: url(@pizza.ImageUrl); ">
                                <div class="card-img-overlay d-flex flex-column">
                                    <div class="card-body">
                                        <h4 class="card-title mt-0 ">@pizza.Name</h4>
                                    </div>
                                    <div class="card-footer">
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                }
        </div>
  
    </div>
    </section>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la mia pizzeria static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark mb-3">
            <div class="container-fluid justify-content-around">
                <a class="navbar-brand me-5" asp-area="" asp-controller="Pizze" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 text-center">
                        <li class="nav-item flex-grow-1">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Home" asp-action="Prenota">Prenota</a>
                        </li>
                        <li class="nav-item flex-grow-1">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Home" asp-action="Impasto">Impasto</a>
                        </li>
                        <li class="nav-item flex-grow-1">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Home" asp-action="Contatti">Contatti</a>
                        </li>
                        <li class="nav-item flex-grow-1">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Pizze" asp-action="CreateForm">Aggiungi Pizza</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row text-center mt-5">
                <div class="col">
                    <h5>DOVE SIAMO</h5>
                    <p>
                        Via Raiberti, 14 – Monza <br />20900
                    </p>
                    <p>
                        Corso Matteotti 44 – Seregno <br />20831
                    </p>
                </div>
                <div class="col">
                    <h5>ORARI MONZA</h5>
                    <p>
                        Lun-Ven <br />19.00/23.30
                    </p
                    <p>
                        Sab-Dom <br />12.00/15.00<br />19.00/23.30
                    </p>
                </div>
                <div class="col">
                    <h5>ORARI SEREGNO</h5>
                    <p>
                        Lun-Ven <br />19.00/23.30
                    </p>
                    <p>
                        Sab-Dom <br />12.00/14.30<br />19.00/23.30
                    </p>
                </div>
                <div class="col">
                    <h5>CONTATTI</h5>
                    <p>
                        Tel. Monza: 039 2911871<br />
                        Tel. Seregno 0362 284965<br />
                        Info@bollepizzeria.it<br />
                        seregno@bollepizzeria.it
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>